version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sogood_postgres
    environment:
      POSTGRES_USER: sogood_user
      POSTGRES_PASSWORD: sogood_password
      POSTGRES_DB: sogood_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sogood_user -d sogood_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: sogood_api
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=sogood_user
      - DB_PASSWORD=sogood_password
      - DB_NAME=sogood_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: 