version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: sogood_cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=SoGoodCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "SELECT release_version FROM system.local"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  api:
    build: .
    container_name: sogood_api
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_KEYSPACE=sogood
      - CASSANDRA_DATACENTER=datacenter1
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  cassandra_data: 